# This is a basic workflow to help you get started with Actions

name: .NET Framework 4.8 Action

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Restore NuGet packages
        run: nuget restore AppAutoUpdate.sln
      
      - name: Build the Solution
        run: msbuild AppAutoUpdate.sln /p:Configuration=Release
        
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: D:\a\app-auto-update-test\app-auto-update-test\Installer\bin\Release\Installer.exe
          destination: s3://hainn/local_file.exe
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
