# This is a basic workflow to help you get started with Actions

name: .NET Framework 4.8 Action

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8.x'
        
    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Build and test
      run: |
        msbuild AppAutoUpdate.sln /p:Configuration=Release
        dotnet test Installer\Installer.csproj
